apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: argocd-demo-express-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Minhaz00/Demo-ArgoCD.git
    targetRevision: HEAD
    path: Manifest

  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
    
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
