apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-demo-express-app-deployment
  labels:
    app: argocd-demo-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-demo-express-app
  template:
    metadata:
      labels:
        app: argocd-demo-express-app
    spec:
      containers:
      - name: argocd-demo-express-app
        image: minhaz71/argocd-demo-express-app:1.0
        ports:
        - containerPort: 3000