apiVersion: v1
kind: Service
metadata:
  name: argocd-demo-express-app-service
spec:
  selector:
    app: argocd-demo-express-app
  ports:
  - port: 80
    nodePort: 30080
    targetPort: 3000
    protocol: TCP
  type: NodePort
